// <auto-generated />
using IP_AmazonFreshIndia_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IP_AmazonFreshIndia_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("VendorId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Fruits",
                            Name = "Jammu Apple",
                            SoldCount = 10,
                            Unit = "LB",
                            UnitPrice = 2.99m,
                            VendorId = 1,
                            WarehouseId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Grocery",
                            Name = "Himalayan Honey",
                            SoldCount = 15,
                            Unit = "Box",
                            UnitPrice = 5.49m,
                            VendorId = 2,
                            WarehouseId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Spices",
                            Name = "Kashmiri Saffron",
                            SoldCount = 20,
                            Unit = "Gram",
                            UnitPrice = 25.99m,
                            VendorId = 1,
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            VendorId = 1,
                            Name = "Sunrise Orchid"
                        },
                        new
                        {
                            VendorId = 2,
                            Name = "Mountain Fresh"
                        });
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseId = 1,
                            Name = "Chennai"
                        },
                        new
                        {
                            WarehouseId = 2,
                            Name = "Delhi"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
